export type User = {
  id: string;
  first_name: string;
  last_name: string;
  full_name: string;
  username: string;
  email: string;
  phone: string;
  password: string;
  birthday: string;
  gender: string;
  fa2_status: string;
  remember_token: string;
  avatar: string;
  cart: string;
  newsletter: string;
  ip: string;
  role_id: string;
  status: string;
  flg_change_pwd: string;
  country_code: string;
};
